### ISSUE TITLE
Does not load with Remote SSH connection

### ISSUE THREAD

**Issue by austinbutler** [nix-community/vscode-nix-ide#203]
I'm using a local VS Code on macOS to connect to a remote NixOS server using the [Remote - SSH extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh).

I have NixIDE installed on my local VS Code and in the SSH remote. Locally it works properly, but when opening a remote project I see this in the "Log (Remote Extension Host)":
```
[2022-02-03 22:12:51.470] [exthost] [error] Activating extension jnoortheen.nix-ide failed due to an error:
[2022-02-03 22:12:51.470] [exthost] [error] null
```

**Comment by darichey** [comment]
I am getting this same error while _not_ using Remote SSH.

**Comment by darichey** [comment]
This happens when `rnix-lsp` is not installed/can't be located at `nix.serverPath`.

I think this is due to a bug in `command-exists`. In this code:
https://github.com/mathisonian/command-exists/blob/742a73d75e6ff737c35aa7c88d0828cbb0455811/lib/command-exists.js#L135-L139
`output` is false (i.e., the command does not exist), but that doesn't mean there was an error (`error` is null).
